_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 30
                - 50
                - 53
                - 55
            "2":
                - 1
                - 5
                - 30
                - 50
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
device:
    value: cpu
env:
    value:
        decay: 0.99
        harden_gaps: 0
        num_rollouts: 8
        num_steps: 50
model:
    value:
        depth: 2
        features: 19
        hidden_dim: 512
        n_layers: 1
optimization:
    value:
        batchsize: 128
        gae: 0.9
        lr: 5e-05
training_scheme:
    value:
        clip_coef: 0.1
        clip_vloss: true
        ent_coef: 0.01
        max_grad_norm: 0.5
        name: PPO
        norm_adv: true
        update_epochs: 16
        vf_coef: 0.5
